### ISSUE TITLE
Missing mc2d.T_clean.Rda in this git directory

### ISSUE THREAD

**Issue by EricHCKim** [kenxie7/ZmanR#1]
Hello, I read your gorgeous article yesterday.
Thus, I wanted to copy your code to make the same figure.
However, because there isn't mc2d.T_clean.Rda file in your mc_example folder, tutorial code doesn't work.

Please upload mc2d.T_clean.Rda :)

Thank you for reading.

**Comment by kenxie7** [comment]
Hi Eric!

Thanks for pointing that out, I have uploaded the required data object for the example code. 

Best,
Ken
